import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';

const fakeData = [
    {
      "id": 102519615,
      "name": "github-traffic-views",
      "full_name": "dance2die/github-traffic-views",
      "owner": {
        "login": "dance2die",
        "id": 8465237,
        "avatar_url": "https://avatars1.githubusercontent.com/u/8465237?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dance2die",
        "html_url": "https://github.com/dance2die",
        "followers_url": "https://api.github.com/users/dance2die/followers",
        "following_url": "https://api.github.com/users/dance2die/following{/other_user}",
        "gists_url": "https://api.github.com/users/dance2die/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dance2die/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dance2die/subscriptions",
        "organizations_url": "https://api.github.com/users/dance2die/orgs",
        "repos_url": "https://api.github.com/users/dance2die/repos",
        "events_url": "https://api.github.com/users/dance2die/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dance2die/received_events",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://github.com/dance2die/github-traffic-views",
      "description": "List all GitHub repo traffic views graphs in one place.",
      "fork": false,
      "url": "https://api.github.com/repos/dance2die/github-traffic-views",
      "forks_url": "https://api.github.com/repos/dance2die/github-traffic-views/forks",
      "keys_url": "https://api.github.com/repos/dance2die/github-traffic-views/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/dance2die/github-traffic-views/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/dance2die/github-traffic-views/teams",
      "hooks_url": "https://api.github.com/repos/dance2die/github-traffic-views/hooks",
      "issue_events_url": "https://api.github.com/repos/dance2die/github-traffic-views/issues/events{/number}",
      "events_url": "https://api.github.com/repos/dance2die/github-traffic-views/events",
      "assignees_url": "https://api.github.com/repos/dance2die/github-traffic-views/assignees{/user}",
      "branches_url": "https://api.github.com/repos/dance2die/github-traffic-views/branches{/branch}",
      "tags_url": "https://api.github.com/repos/dance2die/github-traffic-views/tags",
      "blobs_url": "https://api.github.com/repos/dance2die/github-traffic-views/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/dance2die/github-traffic-views/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/dance2die/github-traffic-views/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/dance2die/github-traffic-views/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/dance2die/github-traffic-views/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/dance2die/github-traffic-views/languages",
      "stargazers_url": "https://api.github.com/repos/dance2die/github-traffic-views/stargazers",
      "contributors_url": "https://api.github.com/repos/dance2die/github-traffic-views/contributors",
      "subscribers_url": "https://api.github.com/repos/dance2die/github-traffic-views/subscribers",
      "subscription_url": "https://api.github.com/repos/dance2die/github-traffic-views/subscription",
      "commits_url": "https://api.github.com/repos/dance2die/github-traffic-views/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/dance2die/github-traffic-views/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/dance2die/github-traffic-views/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/dance2die/github-traffic-views/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/dance2die/github-traffic-views/contents/{+path}",
      "compare_url": "https://api.github.com/repos/dance2die/github-traffic-views/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/dance2die/github-traffic-views/merges",
      "archive_url": "https://api.github.com/repos/dance2die/github-traffic-views/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/dance2die/github-traffic-views/downloads",
      "issues_url": "https://api.github.com/repos/dance2die/github-traffic-views/issues{/number}",
      "pulls_url": "https://api.github.com/repos/dance2die/github-traffic-views/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/dance2die/github-traffic-views/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/dance2die/github-traffic-views/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/dance2die/github-traffic-views/labels{/name}",
      "releases_url": "https://api.github.com/repos/dance2die/github-traffic-views/releases{/id}",
      "deployments_url": "https://api.github.com/repos/dance2die/github-traffic-views/deployments",
      "created_at": "2017-09-05T19:06:09Z",
      "updated_at": "2017-09-05T19:13:31Z",
      "pushed_at": "2017-09-05T19:17:42Z",
      "git_url": "git://github.com/dance2die/github-traffic-views.git",
      "ssh_url": "git@github.com:dance2die/github-traffic-views.git",
      "clone_url": "https://github.com/dance2die/github-traffic-views.git",
      "svn_url": "https://github.com/dance2die/github-traffic-views",
      "homepage": null,
      "size": 0,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": "JavaScript",
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 0,
      "mirror_url": null,
      "open_issues_count": 0,
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "master"
    },
  ]
ReactDOM.render(<App repos={fakeData} />, document.getElementById('root'));

